server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: image-service-quarkus
          uri: http://image-service-quarkus:8083
          predicates:
            - Path=/image/**
          filters:
            - AuthenticationFilter
        - id: project-service-quarkus
          uri: http://project-service-quarkus:8086
          predicates:
            - Path=/project/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
        - id: profile-hr-service
          uri: lb://PROFILE-HR-SERVICE
          predicates:
            - Path=/profile-hr/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
        - id: manager-service
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager/**
          filters:
            - AuthenticationFilter
        - id: email-service-quarkus
          uri: http://email-service-quarkus:8087
          predicates:
            - Path=/email/**

