apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8671/eureka"
  USER_SERVICE_DB_URL: "jdbc:mysql://host.docker.internal:3306/portfolio?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"
  PROJECT_SERVICE_DB_URL: "jdbc:mysql://host.docker.internal:3306/project1?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"
  IMAGE_SERVICE_DB_URL: "jdbc:mysql://host.docker.internal:3306/image?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"
  NOTIFICATION_SERVICE_DB_URL: "jdbc:mysql://host.docker.internal:3306/notification1?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"
  MONGODB_URI: "mongodb://host.docker.internal:27017/microservice-portfolio"
