apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-service-quarkus
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-service-quarkus
  template:
    metadata:
      labels:
        app: manager-service-quarkus
    spec:
      containers:
        - name: manager-service-quarkus
          image: portfolio-manager-service-quarkus:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          env:
            - name: QUARKUS_HTTP_HOST
              value: "0.0.0.0"

            - name: QUARKUS_HTTP_PORT
              value: "8091"

            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: portfolio-config
                  key: MONGODB_URI

            - name: QUARKUS_MONGODB_DATABASE
              value: "microservice-portfolio"
---
apiVersion: v1
kind: Service
metadata:
  name: manager-service-quarkus
  namespace: portfolio
spec:
  type: NodePort
  selector:
    app: manager-service-quarkus
  ports:
    - port: 8091
      targetPort: 8091
      nodePort: 30992