apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-quarkus
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-quarkus
  template:
    metadata:
      labels:
        app: notification-service-quarkus
    spec:
      containers:
        - name: notification-service-quarkus
          image: portfolio-notification-service-quarkus:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: QUARKUS_HTTP_HOST
              value: "0.0.0.0"

            - name: QUARKUS_HTTP_PORT
              value: "8084"

            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: portfolio-config
                  key: NOTIFICATION_SERVICE_DB_URL

            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: MYSQL_USERNAME

            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-quarkus
  namespace: portfolio
spec:
  type: NodePort
  selector:
    app: notification-service-quarkus
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30894